-- ====================================================================
-- EXCUSE.AI — Supabase PostgreSQL Database Schema
-- Run this SQL in your Supabase SQL Editor (Dashboard > SQL Editor > New Query)
-- ====================================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    auth_provider TEXT DEFAULT 'email',
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 2. Sessions Table
CREATE TABLE IF NOT EXISTS public.sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 3. Password Reset Tokens Table
CREATE TABLE IF NOT EXISTS public.password_resets (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    used INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 4. Excuses Table
CREATE TABLE IF NOT EXISTS public.excuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    scenario TEXT NOT NULL,
    urgency TEXT NOT NULL,
    recipient TEXT NOT NULL,
    tone TEXT NOT NULL,
    details TEXT,
    primary_text TEXT NOT NULL,
    variations_json TEXT DEFAULT '[]',
    believability_score INTEGER DEFAULT 95,
    risk_level TEXT DEFAULT 'Low',
    tips_json TEXT DEFAULT '[]',
    is_favorite INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 5. Supporting Documents Table
CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    doc_type TEXT NOT NULL,
    title TEXT NOT NULL,
    recipient TEXT NOT NULL,
    issue_date TEXT NOT NULL,
    organization TEXT NOT NULL,
    content_json TEXT NOT NULL,
    is_favorite INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 6. User Settings Table
CREATE TABLE IF NOT EXISTS public.user_settings (
    user_id BIGINT PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    default_tone TEXT DEFAULT 'Professional',
    default_recipient TEXT DEFAULT 'Manager',
    custom_api_key TEXT,
    theme_preference TEXT DEFAULT 'dark',
    email_notifications INTEGER DEFAULT 1
);

-- Create Indexes for High Performance
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (email);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON public.sessions (token);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON public.sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_excuses_user_id ON public.excuses (user_id);
CREATE INDEX IF NOT EXISTS idx_excuses_created_at ON public.excuses (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_documents_user_id ON public.documents (user_id);
CREATE INDEX IF NOT EXISTS idx_documents_created_at ON public.documents (created_at DESC);

-- Enable Row Level Security (RLS) - Optional
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.password_resets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.excuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- Allow service role & backend connection full access
CREATE POLICY "Allow all access to service role on users" ON public.users FOR ALL USING (true);
CREATE POLICY "Allow all access to service role on sessions" ON public.sessions FOR ALL USING (true);
CREATE POLICY "Allow all access to service role on password_resets" ON public.password_resets FOR ALL USING (true);
CREATE POLICY "Allow all access to service role on excuses" ON public.excuses FOR ALL USING (true);
CREATE POLICY "Allow all access to service role on documents" ON public.documents FOR ALL USING (true);
CREATE POLICY "Allow all access to service role on user_settings" ON public.user_settings FOR ALL USING (true);
